name: Install to Ubuntu
on:
  schedule:
    - cron: |
        0 0 * * *
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  install:
    name: Install to Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "ubuntu:20.04"
            package: mysql
          - image: "ubuntu:22.04"
            package: mariadb
          - image: "ubuntu:22.04"
            package: mysql
    steps:
      - uses: actions/checkout@v4
      - uses: canonical/setup-lxd@v0.1.1
      - name: Prepare container
        run: |
          set -x
          lxc launch ${{ matrix.image }} target
          lxc config device add target host disk source=$PWD path=/host
          sleep 1 # Wait for systemd ready
          lxc exec target -- systemctl is-system-running --wait
      - name: Install Mroonga
        run: |
          lxc exec target -- /host/packages/apt/install_test.sh ${{ matrix.package }}-mroonga
          lxc stop target
          lxc delete target
